// const MandameUnAudio = {
// 	'title' : `Mándame Un Audio (Remix)`,
// 	'artists' : `Fresquito y Mango, Aitana`,
// 	'totalTime' : `03:28`,
// 	'0' : [1, `Y hoy he tenido cita con mi psicólogo`],
// 	'3.5' : [2, `Y me ha pedido que de ti no hable más`],
// 	'5.5' : [3, `Que nunca ha visto nada parecido`],
// 	'8.5' : [4, `Que nos envidia y no lo puede aguantar`],
// 	'11' : [5, `Llevo tres días sin parar de pensar`],
// 	'14' : [6, `Que tu cara no la recuerdo ya`],
// 	'16.5' : [7, `Solo porque no nos vemos tantísimo`],
// 	'19.5' : [8, `Todo lo que me podría gustar`],
// 	'22' : [9, `Mañana sale de aquí un ave carísimo`],
// 	'25' : [10, `No me lo puedo permitir`],
// 	'27.5' : [11, `Y los buses es que tardan muchísimo`],
// 	'30.5' : [12, `Y este dilema no me deja dormir`],
// 	'33' : [13, `He decidido que te voy a llamar`],
// 	'35.5' : [14, `Me empaparía si supiera llorar`],
// 	'38.5' : [15, `Pero hace varios años que no me acuerdo`],
// 	'41' : [16, `Cómo se hace, no te voy a engañar`],
// 	'44' : [17, `Y aunque digas`],
// 	'46.5' : [18, `Que estás enfadada `],
// 	'48.5' : [19, `Y cuelgues mis llamadas`],
// 	'51.5' : [20, `Sé que mueres`],
// 	'53' : [21, `Por volverme a ver`],
// 	'55.5' : [22, `Mándame un audio`],
// 	'57' : [23, `Y dime que me quieres`],
// 	'58' : [24, `Dime dónde estás`],
// 	'59' : [25, `Que te paso a buscar`],
// 	'60.5' : [26, `Que todo está bien`],
// 	'62' : [27, `Que me quieres ver`],
// 	'63.5' : [28, `Ya no me ponen triste tus mensajes de ayer`],
// 	'66.5' : [29, `Mándame un audio`],
// 	'68' : [30, `Y dime que me quieres`],
// 	'69' : [31, `Dime dónde estás`],
// 	'70.5' : [32, `Que te paso a buscar`],
// 	'71.8' : [33, `Que todo está bien`],
// 	'73' : [34, `Que me quieres ver`],
// 	'74.5' : [35, `Ya no me ponen triste tus mensajes de ayer`],
// 	'77.5' : [36, `Me vas a matar`],
// 	'79' : [37, `Y no quiero ser pesado`],
// 	'80.5' : [38, `Me voy a morir`],
// 	'81.5' : [39, `Si no te tengo a mi lado`],
// 	'83' : [40, `Y ahora estoy arriba`],
// 	'84.5' : [41, `Pensando en lo que ha pasado`],
// 	'86' : [42, `Mirando a la luna`],
// 	'87' : [43, `Sentadito en el tejado`],
// 	'88.5' : [44, `Y cada noche que pasa sin ti estoy más solo`],
// 	'91.5' : [45, `Y cada día me tienes un poco más loco`],
// 	'94' : [46, `Lo que tú me haces sentir yo ya no lo controlo`],
// 	'96.5' : [47, `Pero no sé si podré ir`],
// 	'98.5' : [48, `Y es que ahora`],
// 	'100.5' : [49, `Que piensas que me he olvidado de todo`],
// 	'103' : [50, `Las veces que pasé la noche a solas`],
// 	'106' : [51, `Tratando de sacarte de algún modo`],
// 	'108.6' : [52, `De mi cabeza`],
// 	'110.2' : [53, `Y otra`],
// 	'111.6' : [54, `Vez pensando que ya queda poco`],
// 	'114.3' : [55, `Que sigue en mi maleta tu ropa`],
// 	'116.8' : [56, `Todos lo sabían menos nosotros`],
// 	'119.5' : [57, `Menos nosotros`],
// 	'120.5' : [58, `Y aunque digas`],
// 	'122.5' : [59, `Que estás enfadada y`],
// 	'125.3' : [60, `Cuelgues mis llamadas`],
// 	'128' : [61, `Sé que mueres`],
// 	'129' : [62, `Por volverme a ver`],
// 	'132' : [63, `Mándame un audio`],
// 	'133.5' : [64, `Y Dime que me quieres`],
// 	'134.5' : [65, `Dime dónde estás`],
// 	'136' : [66, `Que te paso a buscar`],
// 	'137.2' : [67, `Que todo está bien`],
// 	'138.5' : [68, `Que me quieres ver`],
// 	'140' : [69, `Ya no me ponen triste tus mensajes de ayer`],
// 	'142.8' : [70, `Mándame un audio`],
// 	'144.3' : [71, `Y Dime que me quieres`],
// 	'145.3' : [72, `Dime dónde estás`],
// 	'147' : [73, `Que te paso a buscar`],
// 	'148.1' : [74, `Que todo está bien`],
// 	'149.5' : [75, `Que me quieres ver`],
// 	'150.8' : [76, `Ya no me ponen triste tus mensajes de ayer`],
// 	'154' : [77, `Mándame un audio (y no quiero ser pasado)`],
// 	'156.5' : [78, `Y dime que me quieres (si no te tengo a mi lado)`],
// 	'159.3' : [79, `Dime dónde estás (pensando en lo que ha pasado)`],
// 	'162' : [80, `Que yo te quiero ver más (sentadita en el tejado)`],
// 	'164.8' : [81, `Mándame un audio (y no quiero ser pasado)`],
// 	'167.8' : [82, `Y dime que me quieres (si no te tengo a mi lado)`],
// 	'170.5' : [83, `Dime dónde estás (pensando en lo que ha pasado)`],
// 	'172.3' : [84, `Que yo te quiero ver más (sentadita en el tejado)`],
// 	'175.3' : [85, `Mándame un audio`],
// 	'177' : [86, `Y Dime que me quieres`],
// 	'178.1' : [87, `Dime dónde estás`],
// 	'179.5' : [88, `Que te paso a buscar`],
// 	'180.8' : [89, `Que todo está bien`],
// 	'182.2' : [90, `Que me quieres ver`],
// 	'183.5' : [91, `Ya no me ponen triste tus mensajes de ayer`],
// 	'186.5' : [92, `Mándame un audio`],
// 	'187.8' : [93, `Y dime que me quieres`],
// 	'189' : [94, `Dime dónde estás`],
// 	'190.4' : [95, `que te paso a buscar`],
// 	'191.7' : [96, `Que todo está bien`],
// 	'193' : [97, `Que me quieres ver`],
// 	'194.5' : [98, `Ya no me ponen triste tus mensajes de ayer...`],
// }
const MandameUnAudio = {
	'title' : `Mándame Un Audio (Remix)`,
	'artists' : `Fresquito y Mango, Aitana`,
	'totalTime' : `03:28`,
	'0' : [1, `Y hoy he tenido cita con mi psicólogo`],
	'3' : [2, `Y me ha pedido que de ti no hable más`],
	'5' : [3, `Que nunca ha visto nada parecido`],
	'8' : [4, `Que nos envidia y no lo puede aguantar`],
	'11' : [5, `Llevo tres días sin parar de pensar`],
	'14' : [6, `Que tu cara no la recuerdo ya`],
	'16' : [7, `Solo porque no nos vemos tantísimo`],
	'19' : [8, `Todo lo que me podría gustar`],
	'22' : [9, `Mañana sale de aquí un ave carísimo`],
	'25' : [10, `No me lo puedo permitir`],
	'27' : [11, `Y los buses es que tardan muchísimo`],
	'30' : [12, `Y este dilema no me deja dormir`],
	'33' : [13, `He decidido que te voy a llamar`],
	'35' : [14, `Me empaparía si supiera llorar`],
	'38' : [15, `Pero hace varios años que no me acuerdo`],
	'41' : [16, `Cómo se hace, no te voy a engañar`],
	'44' : [17, `Y aunque digas`],
	'46' : [18, `Que estás enfadada `],
	'48' : [19, `Y cuelgues mis llamadas`],
	'51' : [20, `Sé que mueres`],
	'53' : [21, `Por volverme a ver`],
	'55' : [22, `Mándame un audio`],
	'57' : [23, `Y dime que me quieres`],
	'58' : [24, `Dime dónde estás`],
	'59' : [25, `Que te paso a buscar`],
	'60' : [26, `Que todo está bien`],
	'62' : [27, `Que me quieres ver`],
	'63' : [28, `Ya no me ponen triste tus mensajes de ayer`],
	'66' : [29, `Mándame un audio`],
	'68' : [30, `Y dime que me quieres`],
	'69' : [31, `Dime dónde estás`],
	'70' : [32, `Que te paso a buscar`],
	'72' : [33, `Que todo está bien`],
	'73' : [34, `Que me quieres ver`],
	'74' : [35, `Ya no me ponen triste tus mensajes de ayer`],
	'77' : [36, `Me vas a matar`],
	'79' : [37, `Y no quiero ser pesado`],
	'80' : [38, `Me voy a morir`],
	'81' : [39, `Si no te tengo a mi lado`],
	'83' : [40, `Y ahora estoy arriba`],
	'84' : [41, `Pensando en lo que ha pasado`],
	'86' : [42, `Mirando a la luna`],
	'87' : [43, `Sentadito en el tejado`],
	'88' : [44, `Y cada noche que pasa sin ti estoy más solo`],
	'91' : [45, `Y cada día me tienes un poco más loco`],
	'94' : [46, `Lo que tú me haces sentir yo ya no lo controlo`],
	'96' : [47, `Pero no sé si podré ir`],
	'98' : [48, `Y es que ahora`],
	'100' : [49, `Que piensas que me he olvidado de todo`],
	'103' : [50, `Las veces que pasé la noche a solas`],
	'106' : [51, `Tratando de sacarte de algún modo`],
	'109' : [52, `De mi cabeza`],
	'110' : [53, `Y otra`],
	'112' : [54, `Vez pensando que ya queda poco`],
	'114' : [55, `Que sigue en mi maleta tu ropa`],
	'117' : [56, `Todos lo sabían menos nosotros`],
	'119' : [57, `Menos nosotros`],
	'120' : [58, `Y aunque digas`],
	'122' : [59, `Que estás enfadada y`],
	'125' : [60, `Cuelgues mis llamadas`],
	'128' : [61, `Sé que mueres`],
	'129' : [62, `Por volverme a ver`],
	'132' : [63, `Mándame un audio`],
	'133' : [64, `Y Dime que me quieres`],
	'134' : [65, `Dime dónde estás`],
	'136' : [66, `Que te paso a buscar`],
	'137' : [67, `Que todo está bien`],
	'138' : [68, `Que me quieres ver`],
	'140' : [69, `Ya no me ponen triste tus mensajes de ayer`],
	'143' : [70, `Mándame un audio`],
	'144' : [71, `Y Dime que me quieres`],
	'145' : [72, `Dime dónde estás`],
	'147' : [73, `Que te paso a buscar`],
	'148' : [74, `Que todo está bien`],
	'149' : [75, `Que me quieres ver`],
	'151' : [76, `Ya no me ponen triste tus mensajes de ayer`],
	'154' : [77, `Mándame un audio (y no quiero ser pasado)`],
	'156' : [78, `Y dime que me quieres (si no te tengo a mi lado)`],
	'159' : [79, `Dime dónde estás (pensando en lo que ha pasado)`],
	'162' : [80, `Que yo te quiero ver más (sentadita en el tejado)`],
	'165' : [81, `Mándame un audio (y no quiero ser pasado)`],
	'168' : [82, `Y dime que me quieres (si no te tengo a mi lado)`],
	'170' : [83, `Dime dónde estás (pensando en lo que ha pasado)`],
	'172' : [84, `Que yo te quiero ver más (sentadita en el tejado)`],
	'175' : [85, `Mándame un audio`],
	'177' : [86, `Y Dime que me quieres`],
	'178' : [87, `Dime dónde estás`],
	'179' : [88, `Que te paso a buscar`],
	'181' : [89, `Que todo está bien`],
	'182' : [90, `Que me quieres ver`],
	'183' : [91, `Ya no me ponen triste tus mensajes de ayer`],
	'186' : [92, `Mándame un audio`],
	'188' : [93, `Y dime que me quieres`],
	'189' : [94, `Dime dónde estás`],
	'190' : [95, `Que te paso a buscar`],
	'192' : [96, `Que todo está bien`],
	'193' : [97, `Que me quieres ver`],
	'194' : [98, `Ya no me ponen triste tus mensajes de ayer.`],
}




















