const WaitingForLove = {
	'title' : `Waiting For Love`,
	'artists' : `Avicii`,
	'totalTime' : `03:50`,
	'0' : [1, `•••♪♫♩•••`],
	'10' : [2, `Where there's a will, there's a way, kind of beautiful`],
	'14' : [3, `And every night has its day, so magical`],
	'18' : [4, `And if there's love in this life, there's no obstacle`],
	'21' : [5, `That can't be defeated`],
	'25' : [6, `For every tyrant, a tear for the vulnerable`],
	'29' : [7, `In every lost soul, the bones of a miracle`],
	'33' : [8, `For every dreamer, a dream, we're unstoppable`],
	'36' : [9, `With something to believe in`],
	'41' : [10, `Monday left me broken`],
	'44' : [11, `Tuesday, I was through with hoping`],
	'47' : [12, `Wednesday, my empty arms were open`],
	'51' : [13, `Thursday, waiting for love, waiting for love`],
	'56' : [14, `Thank the stars, it's Friday`],
	'58' : [15, `I'm burning like a fire gone wild on Saturday`],
	'62' : [16, `Guess I won't be coming to church on Sunday`],
	'66' : [17, `I'll be waiting for love, waiting for love to come around`],
	'77' : [18, `•••♪♫♩•••`],
	'123' : [19, `We are one of a kind, irreplaceable`],
	'126' : [20, `How did I get so blind and so cynical?`],
	'130' : [21, `If there's love in this life, we're unstoppable`],
	'134' : [22, `No, we can't be defeated`],
	'138' : [23, `Monday left me broken`],
	'141' : [24, `Tuesday, I was through with hoping`],
	'145' : [25, `Wednesday, my empty arms were open`],
	'148' : [26, `Thursday, waiting for love, waiting for love`],
	'153' : [27, `Thank the stars, it's Friday`],
	'156' : [28, `I'm burning like a fire gone wild on Saturday`],
	'160' : [29, `Guess I won't be coming to church on Sunday`],
	'163' : [30, `I'll be waiting for love, waiting for love to come around`],
	'173' : [31, `•••♪♫♩•••`],
}